config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  get 'users/profile' => 'users#profile'
  resources :users, only: [:show, :update]
  resources :annonces do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:edit, :update, :show]

  root 'pages#home'

end

app/models/annonce.rb
class Annonce < ActiveRecord::Base
  belongs_to :user

  has_many :bookings
 has_attached_file :picture,
    styles: { medium: "300x300>", thumb: "100x100>" }

  validates_attachment_content_type :picture,
    content_type: /\Aimage\/.*\z/
  # validates :user, presence: true
  # validates :name, presence: true
  # validates :adresse, presence: true
  # validates :price, presence: true
  # validates :child_number, presence: true
  validates :user_id, presence: true

  geocoded_by :adresse
  after_validation :geocode, if: :adresse_changed?
end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
  belongs_to :annonce

  validates :user, presence: true
  validates :annonce, presence: true
  validates :start_at, presence: true
  validates :finish_at, presence: true

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # CHILD = ["1", "2", "3", "4", "5"]

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, omniauth_providers: [:facebook]


  has_many :annonces, dependent: :destroy
  has_many :bookings, dependent: :destroy

  # validates :email, presence: true
  # validates :encrypted_password, presence: true
  # validates :child_number, inclusion: {in: CHILD }

  def self.find_for_facebook_oauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email || "#{auth.info.first_name}.#{auth.info.last_name}@facebook.com"
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.first_name = auth.info.first_name
      user.last_name = auth.info.last_name
      user.picture = auth.info.image
      user.token = auth.credentials.token
      user.token_expiry = Time.at(auth.credentials.expires_at)
    end
  end
end

app/controllers/annonces_controller.rb
class AnnoncesController < ApplicationController

  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_annonce, only: [:show, :update, :edit, :destroy]


  def index
    @annonces = Annonce.all

    # Let's DYNAMICALLY build the markers for the view.

    if params[:city]
      @annonces = Annonce.where(city: params[:city])
    else
      @annonces = Annonce.all
    end

    @markers = Gmaps4rails.build_markers(@annonces) do |annonce, marker|
      marker.lat annonce.latitude
      marker.lng annonce.longitude
    end
  end


  def show
    @markers = Gmaps4rails.build_markers(@annonce) do |annonce, marker|
      marker.lat annonce.latitude
      marker.lng annonce.longitude
    end
  end

  def new
    @annonce = Annonce.new
  end

  def create
    @annonce = current_user.annonces.new(annonce_params)
    @annonce.save
      if @annonce.save
        redirect_to annonce_path(@annonce)
      else
        render :new
      end
  end

  def edit
  end

  def update
    @annonce.update(annonce_params)
    if @annonce.save
      redirect_to annonce_path(@annonce)
    else
      render :edit
    end
  end

  def destroy
    # check the user
    annonce = current_user.annonces.find(params[:id])
    annonce.destroy if annonce
    redirect_to root_path
  end


  private

  def set_annonce
    @annonce = Annonce.find(params[:id])
  end

  def annonce_params
    params.require(:annonce).permit( :name, :adresse, :picture, :city, :price, :description, :child_number, :user_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :authenticate_user!
  protect_from_forgery with: :exception

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController


  before_action :set_booking, only: [:destroy, :show, :edit, :update]
  before_action :set_annonce, except: [:show, :edit, :update]
  skip_before_action :authenticate_user!, only: :show

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.annonce = @annonce
    @booking.user = current_user
    @booking.save
      if @booking.save
        redirect_to booking_path(@booking)
      else
        render :new
      end
  end

  def show
    @time = @booking.finish_at - @booking.start_at
    @minutes = @time/60
    @hours = @minutes/60
    @total_price = @hours*(@booking.annonce.price)
  end

  def destroy
    @booking.delete
    redirect_to root_path
  end

  def edit
    @annonce = @booking.annonce
  end

  def update
    @booking.update(booking_params)
    if @booking.save
      redirect_to annonces_path
    else
      render :edit
    end
  end


  private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_annonce
    @annonce = Annonce.find(params[:annonce_id])
  end

  def booking_params
    params.require(:booking).permit( :message, :start_at, :finish_at)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  skip_before_action :authenticate_user!, only: :home

  def home
  end

end


#   before_action :set_annonce, only: [:show, :update, :edit, :destroy]


#   def new
#     @home = Annonce.new
#   end

#   def create
#     @annonce = Annonce.new(annonce_params)
#       if @annonce.save
#         redirect_to annonce_path(annonce)
#       else
#         render :new
#       end
#   end

#   def edit
#   end

#   def update
#     @annonce = Annonce.update(annonce_params)
#     if @annonce.save
#       redirect_to annonce_path(annonce)
#     else
#       render :edit
#     end
#   end

#   def destroy
#     @annonce.delete
#     redirect_to root_path
#   end

#   private

#   def set_annonce
#     @annonce = Annonce.find(params[:id])
#   end

#   def annonce_params
#     params.require(:annonce).permit( :name, :adresse, :price, :description, :child_number, :user_id)
#   end

# end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      flash[:alert] = "Facebook connection failed, #{user.errors.full_messages.join(',')}"
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_action :authenticate_user!, only: :show
  before_action :set_user, only: [:show, :update]

  def show
  end

  def update
    @user = User.update(user_params)
    if @user.save
      redirect_to root_path
    else
      render :edit
    end
  end

  def profile
   @user = current_user
  end


  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit( :email, :password)
  end


end

app/helpers/annonces_helper.rb
module AnnoncesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :alert   then "alert-danger"
    when :notice  then "alert-success"
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/my_profile_helper.rb
module MyProfileHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/annonces/edit.html.erb
<div class="paddingduh1 paddingtop">
  <h1>Edit your form</h1>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <%= render "shared/form" %>
    </div>
  </div>
</div>

app/views/annonces/index.html.erb
<h1 class="paddingduh1 paddingtop padded text-center"> <strong><span class="rose">Funky Nannies</strong></span> available</h1>
<div class="pad-bottom up">
  <div class="container container-index">
    <div class="row">
      <div class="col-xs-6">
        <div class="row">
            <% @annonces.each do |annonce| %>
              <div class="col-xs-6" >
                <div class="card">
                 <h2><span class="rose"><%= annonce.name %></span></h2>
                  <p><%= annonce.price %> €/hour</p>
                  <p>Capacity :<%= annonce.child_number %> children</p>
                  <p>Addres: <%= annonce.adresse %></p>
                  <p>City :<%= annonce.city %></p>
                  <%= link_to "More", annonce_path(annonce) %>
                </div>
              </div>
            <% end %>
        </div>
      </div>

      <div class="map">
      <div class="col-xs-6">
        <div id="map" style="width: 100%; height: 600px;"></div>
          <% content_for(:after_js) do %>
            <%= javascript_tag do %>
              $(document).on('ready', function() {
                handler = Gmaps.build('Google');
                handler.buildMap({ internal: { id: 'map' } }, function(){
                  markers = handler.addMarkers(<%= raw @markers.to_json %>);
                  handler.bounds.extendWith(markers);
                  handler.fitMapToBounds();
                });
              })
            <% end %>
          <% end %>
      </div>
    </div>
</div>
</div>

app/views/annonces/new.html.erb
<div class="paddingduh1 paddingtop">
  <h1>Create your annonce</h1>
</div>

<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <%= render "shared/form" %>
    </div>
  </div>
</div>

app/views/annonces/show.html.erb
<div class="paddingduh1 paddingtop">
  <h1>Here is the announce of <strong><%= @annonce.name %></strong></h1>
</div>


<div class="container">
  <div class="row">
    <div class="col-xs-6">
      <div class="row">
        <div class="col-xs-6">
          <%= image_tag @annonce.picture.url(:medium, class: "img_show") %>
        </div>

        <div class="col-xs-6">
          <div class=" ">
            <h2><%= @annonce.name %></h2>
            <p>Addres : <%= @annonce.adresse %></p>
            <p>City : <%= @annonce.city %></p>
            <p>Price : <%= @annonce.price %>€/hour</p>
            <p>Capacity : <%= @annonce.child_number %> children</p>
          </div>
        </div>
       </div>
      <div class="row">

        <div class="col-xs-12">
          <p>More info : <%= @annonce.description %></p>
        </div>
      </div>
      <div class="row">
        <div class="col-xs-12  paddbtn">
          <p><%= link_to "Book it", new_annonce_booking_path(@annonce), class: "btn btn-primary"%></p>
          <p><%= link_to "Back to homepage", root_path, class: "btn btn-primary" %></p>
          <%= link_to "Delete", annonce_path(@annonce), method: :delete, class: "btn btn-danger" %>
        </div>
      </div>
    </div>


    <div class="col-xs-6">
      <div class="">
        <div id="map" style="width: 100%; height: 600px;"></div>
        <% content_for(:after_js) do %>
          <%= javascript_tag do %>
            $(document).on('ready', function() {
              handler = Gmaps.build('Google');
              handler.buildMap({ internal: { id: 'map' } }, function(){
                markers = handler.addMarkers(<%= raw @markers.to_json %>);
                handler.bounds.extendWith(markers);
                handler.fitMapToBounds();
              });
            })
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/bookings/edit.html.erb
<div class=padded-booking>
  <h1 class="text-center "> <strong>Final step ! </strong> </h1>
  <h3 class="text-center"> <strong>Finalize</strong> your booking with Super-Nanny : <strong><span class="rose"><%=@annonce.name%></span></strong>!
   </h3>
<div class="container padded-booking">
 <div class="row">
   <div class="col-xs-12 col-sm-6 col-sm-offset-3">
     <%= simple_form_for [ @booking] do |f| %>
       <%= f.input :message, placeholder: "Precise any pieces of information you think are important " %>
       <%= f.input :start_at %>
       <%= f.input :finish_at %>
       <%= f.submit "Send your reservation", class: "btn btn-primary" %>
     <% end %>
   </div>
 </div>
</div>

app/views/bookings/new.html.erb
<div class=padded-booking>
  <h1 class="text-center "> <strong>Final step ! </strong> </h1>
  <h3 class="text-center"> <strong>Finalize</strong> your booking with Super-Nanny : <strong><span class="rose"><%=@annonce.name%></span></strong>!
   </h3>
<div class="container padded-booking">
 <div class="row">
   <div class="col-xs-12 col-sm-6 col-sm-offset-3">
     <%= simple_form_for [@annonce, @booking] do |f| %>
       <%= f.input :message, placeholder: "Precise any pieces of information you think are important " %>
       <%= f.input :start_at %>
       <%= f.input :finish_at %>
       <%= f.submit "Send your reservation", class: "btn btn-primary" %>
     <% end %>
   </div>
 </div>
</div>

app/views/bookings/show.html.erb
    <div class=padded-booking>
      <h1 class="text-center "> <strong>Congratulations !</strong> </h1>
      <h3 class="text-center"> Your reservation has been sent to <strong><span class="rose"><%=@booking.annonce.name %></span></strong>
       successfuly !</h3>


      <div class="text-center marg backgr">
        <h4> <strong>Here are your reservation informations </strong> </h4>
        <p> <strong>Your message :</strong> <%=@booking.message%></p>
        <p> <strong>Your reservation duration is : </strong> <%=@hours%> heure(s)</p>
        <p> <strong>You will pay :</strong> <%=@total_price%>€</p>
        </br>
      </div>
      <p class="text-center" > <strong><span class="rose"><%=@booking.annonce.name %></span></strong> will validate your reservation as soon as possible !</p>
    </div>


</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ginette</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>



</head>
<body>
<%= render 'shared/navbar' %>
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

<%= yield %>
<%= render 'shared/footer' %>

<%= javascript_include_tag "https://maps.google.com/maps/api/js?sensor=false" %>
<%= javascript_include_tag "https://google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js" %>

<%= javascript_include_tag "application", 'data-turbolinks-track' =>true %>
<%= csrf_meta_tags %>
<%= yield(:after_js) %>
</body>
</html>

app/views/pages/home.html.erb
  <div class="banner text-center" style="background-image: url('<%= image_path "Home_page" %>')">
  <div class="banner-gradient"></div>
  <div class="banner-content padded">
    <h1>My Social Workplace</h1>
    <p>Trouvez un espace de travail abordable pour votre social business</p
    <%= link_to t("btn btn-primary btn-lg", default: "propose my services"), new_annonce_path(),  class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</div
<div class ="padded-home">
  <div class = "text-center padded">
   <h2>Trouvez un espace de travail</h2>
  </div>
  <div class="container padded-bottom">
    <div class="row">
      <div class="col-xs-10 col-xs-offset-1">
        <h4>Travaillez au sein d'une entreprise et profitez de potentielles synergies</h4>
        <%= form_tag(annonces_path, method: :get) do %>
          <div class="form-group sm-padded">
            <%= label_tag :ville %>
            <%= text_field_tag :city, nil, placeholder: "Ville", class: "form-control" %>
          </div>
          <div class="form-group sm-padded">
            <%= label_tag :date %>
            <%= text_field_tag :date, nil, placeholder: "DD/MM/YYYY", class: "form-control" %>
          </div>
          <div class="form-group sm-padded">
            <%= label_tag :durée %>
            <%= text_field_tag :durée, nil, placeholder: "Horaires", class: "form-control" %>
          </div>
          <div class="form-group sm-padded">
            <%= label_tag :capacité %>
            <%= text_field_tag :capacité, nil, placeholder: "Capacité d'accueil", class: "form-control" %>
          </div>

       <%= submit_tag "Search", class: "btn btn-primary btn-marged btn-radius" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_footer.html.erb
<div id="footer">
  <div class="container">
    <div class="row">
      <div class="col-xs-4">
        <ul class="list-inline">
          <li><a href=""><i class="fa fa-youtube"></i></a></li>
          <li><a href=""><i class="fa fa-instagram"></i></a></li>
          <li><a href=""><i class="fa fa-facebook"></i></a></li>
          <li><a href=""><i class="fa fa-twitter"></i></a></li>
        </ul>
      </div>
      <div class="col-xs-8 text-right">
        <p>MSW vise à mettre en relation des social business et des entreprises disposant de bureaux inutilisés</p>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <%= form_for @annonce do |f| %>
        <div class="form-group">
          <%= f.label :name %>
          <%= f.text_field :name, placeholder: "Margot Fulconis", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :adresse %>
          <%= f.text_field :adresse, placeholder: "4 Villa Gaudelet", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :city %>
          <%= f.text_field :city, placeholder: "Paris", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, placeholder: "Jeune Nounou aux formes avantageuses, je garde les jeunes papas", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :child_number %>
          <%= f.text_field :child_number, placeholder: "4", class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :price %>
          <%= f.text_field :price, placeholder: "20€/h", class: "form-control" %>
        </div>

        <div class="form-group">
        <%= f.label :picture %>
        <%= f.file_field :picture, class: "form-control"  %>
        </div>
        <%= f.submit "Enregistrer l'annonce", class: "btn btn-primary" %>

      <% end %>

    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar-wagon">
  <div class="container navbar-wagon-container">

    <a href="/">
      <%= image_tag "logo MSW2.png", class: "navbar-wagon-logo" %>
    </a>

    <div class="navbar-wagon-pusher"></div>


    <hr class="hidden-xs hidden-sm">
    <% if user_signed_in? %>
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link hidden-xs" do %>

      <% end %>
      <hr>
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag current_user.picture, class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "/users/profile" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "/" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>

      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
    <hr>
    <%= link_to t(".top_call_to_action", default: "All annonces"), "/annonces", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>
</nav>

app/views/users/edit.html.erb
<div class="col-xs-10 col-xs-offset-1">
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name, class: "form-control" %>
    </div>

    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>

</div>

app/views/users/profile.html.erb
<div class=padded-booking>
  <h1 class="text-center "> Hey <strong><span class="rose"><%=@user.first_name%> </span></strong> </h1>
  <div class= "text-center"><%=image_tag current_user.picture, class: "avatar-large avatar-bordered" %></div>
<div class="text-center">
  <% if @user.annonces.any? %>
  <div class="row">
    <div class="col-xs-6">
      <strong><h3>My annonces</h3></strong>

      <% @user.annonces.each do |annonce| %>
        <P><%= annonce.name %></p>
        <p><%= annonce.adresse %></p>
        <p><%= annonce.price %></p>
        <p><%= annonce.description %></p>
        <p><%= annonce.child_number %></p>
      <p><%= link_to 'Edit your annonce', edit_annonce_path(annonce), class: "btn btn-primary" %></p>
      <% end %>
    <% end %>
    </div>
    <div class="col-xs-6">
  <% if @user.bookings.any? %>
     <strong><h3>My reservation</h3></strong>

    <% @user.bookings.each do |booking| %>
      <%= booking.start_at %>
      <%= booking.finish_at %>
      <%= booking.message %>
    <p><%= link_to 'Edit your booking', edit_booking_path(booking), class: "btn btn-primary" %></p>
    <% end %>
  <% end %>
  </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="text-center">
  <h1 >Show user <%= @user.first_name%></h1>

</div>